server:
  port: 8080
  servlet:
    context-path: /mysecurity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/register?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

